import { Hono } from "hono";
import { Bindings, Variables } from "../index";
import { authMiddleware } from "../middleware/auth";
import type { SupabaseLinkRecord } from "../types/supabase";

const githubRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

githubRouter.use("*", authMiddleware);

githubRouter.post("/push", async (c) => {
  const userId = c.get("userId");
  const kv = c.env.KV_METADATA;
  const githubToken = c.env.GITHUB_PAT;

  if (!githubToken) {
    return c.json({ error: "GitHub PAT not configured on the server" }, 500);
  }

  try {
    const { repoName, files, projectId } = await c.req.json();

    if (!repoName || !files) {
      return c.json({ error: "Missing repoName or files" }, 400);
    }

    // Step 1: Get the authenticated GitHub user
    const userRes = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
      },
    });

    if (!userRes.ok) {
      return c.json({ error: "GitHub authentication failed. Check your PAT." }, 401);
    }

    const githubUser = await userRes.json() as { login: string };
    const owner = githubUser.login;

    // Step 2: Create the repo (or use existing)
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Generated by Lovable Clone (project ${projectId})`,
        private: false,
        auto_init: true,
      }),
    });

    // 422 means repo already exists, which is fine
    if (!createRes.ok && createRes.status !== 422) {
      const err = await createRes.text();
      return c.json({ error: `Failed to create repo: ${err}` }, 500);
    }

    // Inject .env.example if Supabase is linked
    const supabaseLinkRaw = await kv.get(`project:${projectId}:supabase`);
    if (supabaseLinkRaw) {
      const link: SupabaseLinkRecord = JSON.parse(supabaseLinkRaw);
      files[".env.example"] =
        `VITE_SUPABASE_URL=${link.restUrl}\nVITE_SUPABASE_ANON_KEY=${link.anonKey}\n`;
    }

    // Step 3: Push all files using the Contents API (simple, works for <100 files)
    const fileEntries = Object.entries(files as Record<string, string>);
    let pushed = 0;
    const errors: string[] = [];

    for (const [filePath, content] of fileEntries) {
      const cleanPath = filePath.startsWith("/") ? filePath.substring(1) : filePath;

      // Base64 encode the content
      const encoded = btoa(unescape(encodeURIComponent(content)));

      // Check if file already exists (to get its SHA for updates)
      let sha: string | undefined;
      const existRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/contents/${cleanPath}`,
        {
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
          },
        }
      );
      if (existRes.ok) {
        const existData = await existRes.json() as { sha: string };
        sha = existData.sha;
      }

      // Create or update the file
      const pushRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/contents/${cleanPath}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message: sha ? `Update ${cleanPath}` : `Add ${cleanPath}`,
            content: encoded,
            ...(sha ? { sha } : {}),
          }),
        }
      );

      if (pushRes.ok) {
        pushed++;
      } else {
        const errText = await pushRes.text();
        errors.push(`${cleanPath}: ${errText.substring(0, 100)}`);
      }
    }

    const repoUrl = `https://github.com/${owner}/${repoName}`;

    return c.json({
      success: true,
      repoUrl,
      pushed,
      total: fileEntries.length,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (error) {
    console.error("GitHub push error:", error);
    return c.json({ error: "Failed to push to GitHub" }, 500);
  }
});

export default githubRouter;
