import { Hono } from "hono";
import { nanoid } from "nanoid";
import { Bindings, Variables } from "../index";
import { authMiddleware } from "../middleware/auth";
import type { SupabaseLinkRecord } from "../types/supabase";

const githubRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

githubRouter.use("*", authMiddleware);

// Parse a GitHub repo reference from the many shapes a user might paste:
//   owner/repo
//   https://github.com/owner/repo(.git)
//   https://github.com/owner/repo/tree/<branch>
//   git@github.com:owner/repo.git
function parseRepoUrl(
  input: string,
): { owner: string; repo: string; branch?: string } | null {
  const s = input.trim();

  // "owner/repo" shorthand (no protocol, no scp-style "@")
  if (!s.includes("://") && !s.includes("@")) {
    const shorthand = /^([\w.-]+)\/([\w.-]+?)(?:\.git)?$/.exec(s);
    if (shorthand) return { owner: shorthand[1], repo: shorthand[2] };
  }

  const normalized = s.replace(/^git@github\.com:/i, "https://github.com/");
  try {
    const u = new URL(normalized);
    if (!/(^|\.)github\.com$/i.test(u.hostname)) return null;
    const parts = u.pathname.replace(/^\/+/, "").split("/").filter(Boolean);
    if (parts.length < 2) return null;
    const owner = parts[0];
    const repo = parts[1].replace(/\.git$/i, "");
    let branch: string | undefined;
    if (parts[2] === "tree" && parts[3]) {
      branch = decodeURIComponent(parts.slice(3).join("/"));
    }
    return { owner, repo, branch };
  } catch {
    return null;
  }
}

githubRouter.post("/push", async (c) => {
  const userId = c.get("userId");
  const kv = c.env.KV_METADATA;
  const githubToken = c.env.GITHUB_PAT;

  if (!githubToken) {
    return c.json({ error: "GitHub PAT not configured on the server" }, 500);
  }

  try {
    const { repoName, files, projectId } = await c.req.json();

    if (!repoName || !files) {
      return c.json({ error: "Missing repoName or files" }, 400);
    }

    // Step 1: Get the authenticated GitHub user
    const userRes = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
      },
    });

    if (!userRes.ok) {
      return c.json({ error: "GitHub authentication failed. Check your PAT." }, 401);
    }

    const githubUser = await userRes.json() as { login: string };
    const owner = githubUser.login;

    // Step 2: Create the repo (or use existing)
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: repoName,
        description: `Generated by HS Solutions App & Web Builder (project ${projectId})`,
        private: false,
        auto_init: true,
      }),
    });

    // 422 means repo already exists, which is fine
    if (!createRes.ok && createRes.status !== 422) {
      const err = await createRes.text();
      return c.json({ error: `Failed to create repo: ${err}` }, 500);
    }

    // Inject .env.example if Supabase is linked
    const supabaseLinkRaw = await kv.get(`project:${projectId}:supabase`);
    if (supabaseLinkRaw) {
      const link: SupabaseLinkRecord = JSON.parse(supabaseLinkRaw);
      files[".env.example"] =
        `VITE_SUPABASE_URL=${link.restUrl}\nVITE_SUPABASE_ANON_KEY=${link.anonKey}\n`;
    }

    // Step 3: Push all files using the Contents API (simple, works for <100 files)
    const fileEntries = Object.entries(files as Record<string, string>);
    let pushed = 0;
    const errors: string[] = [];

    for (const [filePath, content] of fileEntries) {
      const cleanPath = filePath.startsWith("/") ? filePath.substring(1) : filePath;

      // Base64 encode the content
      const encoded = btoa(unescape(encodeURIComponent(content)));

      // Check if file already exists (to get its SHA for updates)
      let sha: string | undefined;
      const existRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/contents/${cleanPath}`,
        {
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
          },
        }
      );
      if (existRes.ok) {
        const existData = await existRes.json() as { sha: string };
        sha = existData.sha;
      }

      // Create or update the file
      const pushRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/contents/${cleanPath}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message: sha ? `Update ${cleanPath}` : `Add ${cleanPath}`,
            content: encoded,
            ...(sha ? { sha } : {}),
          }),
        }
      );

      if (pushRes.ok) {
        pushed++;
      } else {
        const errText = await pushRes.text();
        errors.push(`${cleanPath}: ${errText.substring(0, 100)}`);
      }
    }

    const repoUrl = `https://github.com/${owner}/${repoName}`;

    return c.json({
      success: true,
      repoUrl,
      pushed,
      total: fileEntries.length,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (error) {
    console.error("GitHub push error:", error);
    return c.json({ error: "Failed to push to GitHub" }, 500);
  }
});

// ── Import an existing GitHub repo as a NEW editable project ──────────────────
// Mirrors POST /api/projects: writes KV metadata + an R2 v1.json holding the
// repo's text files as the { "/path": content } map Sandpack/Monaco expect.
// Inverse of /push: /push base64-encodes files OUT; /import base64-decodes IN.
githubRouter.post("/import", async (c) => {
  const userId = c.get("userId");
  const kv = c.env.KV_METADATA;
  const r2 = c.env.R2_PROJECTS;
  const githubToken = c.env.GITHUB_PAT;

  if (!githubToken) {
    return c.json({ error: "GitHub PAT not configured on the server" }, 500);
  }

  const gh = (path: string) =>
    fetch(`https://api.github.com${path}`, {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
      },
    });

  try {
    const { repoUrl, branch } = (await c.req.json()) as {
      repoUrl?: string;
      branch?: string;
    };

    if (!repoUrl || typeof repoUrl !== "string") {
      return c.json({ error: "Missing repoUrl" }, 400);
    }

    const parsed = parseRepoUrl(repoUrl);
    if (!parsed) {
      return c.json(
        { error: "Could not read a GitHub owner/repo from that URL." },
        400,
      );
    }
    const { owner, repo } = parsed;
    let ref = (branch && branch.trim()) || parsed.branch;

    // Resolve the default branch when none was specified.
    const repoRes = await gh(`/repos/${owner}/${repo}`);
    if (repoRes.status === 404) {
      return c.json(
        {
          error:
            "Repo not found, or the server's GitHub token can't see it. Check the URL and that the PAT has access.",
        },
        404,
      );
    }
    if (!repoRes.ok) {
      return c.json(
        { error: `GitHub error fetching repo (${repoRes.status}).` },
        502,
      );
    }
    const repoInfo = (await repoRes.json()) as {
      default_branch: string;
      name: string;
    };
    if (!ref) ref = repoInfo.default_branch;

    // One call gets the whole file tree for the branch.
    const treeRes = await gh(
      `/repos/${owner}/${repo}/git/trees/${encodeURIComponent(ref)}?recursive=1`,
    );
    if (!treeRes.ok) {
      return c.json(
        { error: `Could not read branch "${ref}" (${treeRes.status}).` },
        502,
      );
    }
    const tree = (await treeRes.json()) as {
      tree: { path: string; type: string; sha: string; size?: number }[];
      truncated?: boolean;
    };

    // Limits keep us inside Workers subrequest budgets and R2/Sandpack sanity.
    const MAX_FILE_BYTES = 256 * 1024; // 256 KB per file
    const MAX_FILES = 200;
    const MAX_TOTAL_BYTES = 6 * 1024 * 1024; // 6 MB total

    const SKIP_DIRS =
      /(^|\/)(node_modules|\.git|\.next|dist|build|out|\.turbo|\.vercel|coverage|\.cache|vendor)\//;
    const BINARY_EXT =
      /\.(png|jpe?g|gif|webp|avif|ico|bmp|tiff?|svg|mp4|mov|webm|mp3|wav|ogg|flac|woff2?|ttf|otf|eot|pdf|zip|gz|tgz|tar|rar|7z|exe|dll|so|dylib|wasm|bin|class|jar|psd|sketch|fig|node|map)$/i;
    const SKIP_FILES =
      /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/;

    const blobs = tree.tree.filter((n) => n.type === "blob");
    const skipped: string[] = [];
    const selected: typeof blobs = [];
    let runningTotal = 0;

    for (const n of blobs) {
      const slashed = "/" + n.path;
      if (
        SKIP_DIRS.test(slashed) ||
        BINARY_EXT.test(n.path) ||
        SKIP_FILES.test(n.path)
      ) {
        skipped.push(n.path);
        continue;
      }
      if ((n.size ?? 0) > MAX_FILE_BYTES) {
        skipped.push(`${n.path} (too large)`);
        continue;
      }
      if (selected.length >= MAX_FILES) {
        skipped.push(`${n.path} (file cap)`);
        continue;
      }
      if (runningTotal + (n.size ?? 0) > MAX_TOTAL_BYTES) {
        skipped.push(`${n.path} (size cap)`);
        continue;
      }
      selected.push(n);
      runningTotal += n.size ?? 0;
    }

    if (selected.length === 0) {
      return c.json(
        { error: "No importable text files were found in that repo." },
        400,
      );
    }

    // Fetch each blob (base64) and decode to UTF-8 — inverse of the /push encoder.
    const files: Record<string, string> = {};
    const failed: string[] = [];
    for (const n of selected) {
      try {
        const blobRes = await gh(`/repos/${owner}/${repo}/git/blobs/${n.sha}`);
        if (!blobRes.ok) {
          failed.push(n.path);
          continue;
        }
        const blob = (await blobRes.json()) as {
          content: string;
          encoding: string;
        };
        if (blob.encoding !== "base64") {
          failed.push(n.path);
          continue;
        }
        const decoded = decodeURIComponent(
          escape(atob(blob.content.replace(/\n/g, ""))),
        );
        files["/" + n.path] = decoded;
      } catch {
        failed.push(n.path);
      }
    }

    if (Object.keys(files).length === 0) {
      return c.json(
        { error: "Failed to download any files from that repo." },
        502,
      );
    }

    // Create the project exactly like POST /api/projects does.
    const projectId = nanoid(10);
    const now = new Date().toISOString();
    const project = {
      id: projectId,
      userId,
      name: repoInfo.name || repo,
      description: `Imported from ${owner}/${repo}`,
      createdAt: now,
      updatedAt: now,
    };
    await kv.put(`user:${userId}:project:${projectId}`, JSON.stringify(project));

    const initialVersionData = {
      version: 1,
      createdAt: now,
      prompt: `Imported from https://github.com/${owner}/${repo} (${ref})`,
      files,
    };
    await r2.put(`${projectId}/v1.json`, JSON.stringify(initialVersionData));
    await kv.put(`project:${projectId}:latest_version`, "1");

    return c.json(
      {
        project,
        version: 1,
        imported: Object.keys(files).length,
        skipped: skipped.length,
        failed: failed.length,
        truncated: tree.truncated ?? false,
      },
      201,
    );
  } catch (error) {
    console.error("GitHub import error:", error);
    return c.json(
      {
        error: "Failed to import from GitHub",
        detail: error instanceof Error ? error.message : String(error),
      },
      500,
    );
  }
});

export default githubRouter;
