import { Hono } from "hono";
import { nanoid } from "nanoid";
import { Bindings, Variables } from "../index";
import { authMiddleware, ownerOnly } from "../middleware/auth";
import type { SupabaseLinkRecord } from "../types/supabase";

const githubRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

githubRouter.use("*", authMiddleware);
// Confused-deputy lockdown: uses the shared GitHub PAT (creates repos/pushes
// under the operator's account). Owner-only until per-tenant GitHub auth exists.
githubRouter.use("*", ownerOnly);

// Parse a GitHub repo reference from the many shapes a user might paste:
//   owner/repo
//   https://github.com/owner/repo(.git)
//   https://github.com/owner/repo/tree/<branch>
//   git@github.com:owner/repo.git
function parseRepoUrl(
  input: string,
): { owner: string; repo: string; branch?: string } | null {
  const s = input.trim();

  // "owner/repo" shorthand (no protocol, no scp-style "@")
  if (!s.includes("://") && !s.includes("@")) {
    const shorthand = /^([\w.-]+)\/([\w.-]+?)(?:\.git)?$/.exec(s);
    if (shorthand) return { owner: shorthand[1], repo: shorthand[2] };
  }

  const normalized = s.replace(/^git@github\.com:/i, "https://github.com/");
  try {
    const u = new URL(normalized);
    if (!/(^|\.)github\.com$/i.test(u.hostname)) return null;
    const parts = u.pathname.replace(/^\/+/, "").split("/").filter(Boolean);
    if (parts.length < 2) return null;
    const owner = parts[0];
    const repo = parts[1].replace(/\.git$/i, "");
    let branch: string | undefined;
    if (parts[2] === "tree" && parts[3]) {
      branch = decodeURIComponent(parts.slice(3).join("/"));
    }
    return { owner, repo, branch };
  } catch {
    return null;
  }
}

githubRouter.post("/push", async (c) => {
  const userId = c.get("userId");
  const kv = c.env.KV_METADATA;
  const githubToken = c.env.GITHUB_PAT;

  if (!githubToken) {
    return c.json({ error: "GitHub PAT not configured on the server" }, 500);
  }

  try {
    const { repoName, files, projectId } = await c.req.json();

    if (!repoName || !files) {
      return c.json({ error: "Missing repoName or files" }, 400);
    }

    // Step 1: Get the authenticated GitHub user
    const userRes = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
      },
    });

    if (!userRes.ok) {
      return c.json({ error: "GitHub authentication failed. Check your PAT." }, 401);
    }

    const githubUser = await userRes.json() as { login: string };
    const owner = githubUser.login;

    // Identity persistence: on the first successful push we remember which repo
    // backs this project. On later pushes we reuse THAT repo even if the caller
    // passes a different repoName (e.g. the project was renamed), so we never
    // orphan the original repo by creating a fresh duplicate. The persisted
    // value also wins so files keep landing in one place.
    const repoKey = projectId ? `project:${projectId}:github_repo` : null;
    let targetRepo = repoName as string;
    let reusedExisting = false;
    if (repoKey) {
      const savedRepo = await kv.get(repoKey);
      if (savedRepo) {
        // Stored as the repo's bare name (matches how we use it in the
        // Contents API path below: /repos/{owner}/{repo}). Tolerate a full
        // URL/owner/repo shape from older writes by taking the last segment.
        const trimmed = savedRepo.trim().replace(/\.git$/i, "");
        targetRepo = trimmed.split("/").filter(Boolean).pop() || repoName;
        reusedExisting = true;
      }
    }

    // Step 2: Create the repo (or use existing). When we already have a
    // persisted repo we skip creation entirely (the repo is known to exist) so
    // a rename can never spawn a second repo.
    if (!reusedExisting) {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github+json",
          "User-Agent": "lovable-clone",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: targetRepo,
          description: `Generated by HS Solutions App & Web Builder (project ${projectId})`,
          private: false,
          auto_init: true,
        }),
      });

      // 422 means repo already exists, which is fine
      if (!createRes.ok && createRes.status !== 422) {
        const err = await createRes.text();
        return c.json({ error: `Failed to create repo: ${err}` }, 500);
      }
    }

    // Inject .env.example if Supabase is linked
    const supabaseLinkRaw = await kv.get(`project:${projectId}:supabase`);
    if (supabaseLinkRaw) {
      const link: SupabaseLinkRecord = JSON.parse(supabaseLinkRaw);
      files[".env.example"] =
        `VITE_SUPABASE_URL=${link.restUrl}\nVITE_SUPABASE_ANON_KEY=${link.anonKey}\n`;
    }

    // Step 3: Push all files using the Contents API (simple, works for <100 files)
    const fileEntries = Object.entries(files as Record<string, string>);
    let pushed = 0;
    const errors: string[] = [];

    for (const [filePath, content] of fileEntries) {
      const cleanPath = filePath.startsWith("/") ? filePath.substring(1) : filePath;

      // Base64 encode the content
      const encoded = btoa(unescape(encodeURIComponent(content)));

      // Check if file already exists (to get its SHA for updates)
      let sha: string | undefined;
      const existRes = await fetch(
        `https://api.github.com/repos/${owner}/${targetRepo}/contents/${cleanPath}`,
        {
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
          },
        }
      );
      if (existRes.ok) {
        const existData = await existRes.json() as { sha: string };
        sha = existData.sha;
      }

      // Create or update the file
      const pushRes = await fetch(
        `https://api.github.com/repos/${owner}/${targetRepo}/contents/${cleanPath}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${githubToken}`,
            Accept: "application/vnd.github+json",
            "User-Agent": "lovable-clone",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message: sha ? `Update ${cleanPath}` : `Add ${cleanPath}`,
            content: encoded,
            ...(sha ? { sha } : {}),
          }),
        }
      );

      if (pushRes.ok) {
        pushed++;
      } else {
        const errText = await pushRes.text();
        errors.push(`${cleanPath}: ${errText.substring(0, 100)}`);
      }
    }

    const repoUrl = `https://github.com/${owner}/${targetRepo}`;

    // Persist the repo identity so future pushes for this project reuse it
    // (idempotent). Only write when at least one file landed, so a totally
    // failed push doesn't pin us to a possibly-bad repo. Best-effort: a KV
    // hiccup must not fail an otherwise-successful push.
    if (repoKey && pushed > 0 && !reusedExisting) {
      try {
        await kv.put(repoKey, targetRepo);
      } catch (e) {
        console.error("Failed to persist github_repo key:", e);
      }
    }

    return c.json({
      success: true,
      repoUrl,
      repoName: targetRepo,
      reusedExisting,
      pushed,
      total: fileEntries.length,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (error) {
    console.error("GitHub push error:", error);
    return c.json({ error: "Failed to push to GitHub" }, 500);
  }
});

// ── Import an existing GitHub repo as a NEW editable project ──────────────────
// Mirrors POST /api/projects: writes KV metadata + an R2 v1.json holding the
// repo's text files as the { "/path": content } map Sandpack/Monaco expect.
// Inverse of /push: /push base64-encodes files OUT; /import base64-decodes IN.
githubRouter.post("/import", async (c) => {
  const userId = c.get("userId");
  const kv = c.env.KV_METADATA;
  const r2 = c.env.R2_PROJECTS;
  const githubToken = c.env.GITHUB_PAT;

  if (!githubToken) {
    return c.json({ error: "GitHub PAT not configured on the server" }, 500);
  }

  const gh = (path: string) =>
    fetch(`https://api.github.com${path}`, {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "lovable-clone",
      },
    });

  try {
    const { repoUrl, branch } = (await c.req.json()) as {
      repoUrl?: string;
      branch?: string;
    };

    if (!repoUrl || typeof repoUrl !== "string") {
      return c.json({ error: "Missing repoUrl" }, 400);
    }

    const parsed = parseRepoUrl(repoUrl);
    if (!parsed) {
      return c.json(
        { error: "Could not read a GitHub owner/repo from that URL." },
        400,
      );
    }
    const { owner, repo } = parsed;
    let ref = (branch && branch.trim()) || parsed.branch;

    // Resolve the default branch when none was specified.
    const repoRes = await gh(`/repos/${owner}/${repo}`);
    if (repoRes.status === 404) {
      return c.json(
        {
          error:
            "Repo not found, or the server's GitHub token can't see it. Check the URL and that the PAT has access.",
        },
        404,
      );
    }
    if (!repoRes.ok) {
      return c.json(
        { error: `GitHub error fetching repo (${repoRes.status}).` },
        502,
      );
    }
    const repoInfo = (await repoRes.json()) as {
      default_branch: string;
      name: string;
    };
    if (!ref) ref = repoInfo.default_branch;

    // One call gets the whole file tree for the branch.
    const treeRes = await gh(
      `/repos/${owner}/${repo}/git/trees/${encodeURIComponent(ref)}?recursive=1`,
    );
    if (!treeRes.ok) {
      return c.json(
        { error: `Could not read branch "${ref}" (${treeRes.status}).` },
        502,
      );
    }
    const tree = (await treeRes.json()) as {
      tree: { path: string; type: string; sha: string; size?: number }[];
      truncated?: boolean;
    };

    // Limits keep us inside Workers subrequest budgets and R2/Sandpack sanity.
    const MAX_FILE_BYTES = 256 * 1024; // 256 KB per text file
    const MAX_FILES = 200;
    const MAX_TOTAL_BYTES = 6 * 1024 * 1024; // 6 MB total (text)
    // Raster images are inlined as data: URIs so the preview renders them. They
    // get their own budget so an image-heavy repo can't starve source files or
    // blow up the project JSON (base64 adds ~33%).
    const MAX_IMAGE_FILE_BYTES = 512 * 1024; // 512 KB per image
    const MAX_IMAGE_TOTAL_BYTES = 3 * 1024 * 1024; // 3 MB of images total

    const SKIP_DIRS =
      /(^|\/)(node_modules|\.git|\.next|dist|build|out|\.turbo|\.vercel|coverage|\.cache|vendor)\//;
    // Raster images (png/jpg/…) are NOT skipped — they're fetched separately and
    // stored as data: URIs (see the image pass below) so they render in preview.
    // .svg is also kept (as text). Everything below is genuinely un-inlinable
    // binary (fonts/video/audio/archives/etc.) and stays skipped.
    const IMAGE_EXT = /\.(png|jpe?g|gif|webp|avif|ico|bmp)$/i;
    const IMAGE_MIME: Record<string, string> = {
      png: "image/png",
      jpg: "image/jpeg",
      jpeg: "image/jpeg",
      gif: "image/gif",
      webp: "image/webp",
      avif: "image/avif",
      ico: "image/x-icon",
      bmp: "image/bmp",
    };
    const BINARY_EXT =
      /\.(tiff?|mp4|mov|webm|mp3|wav|ogg|flac|woff2?|ttf|otf|eot|pdf|zip|gz|tgz|tar|rar|7z|exe|dll|so|dylib|wasm|bin|class|jar|psd|sketch|fig|node|map)$/i;
    const SKIP_FILES =
      /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/;

    const blobs = tree.tree.filter((n) => n.type === "blob");
    const skipped: string[] = [];
    const selected: typeof blobs = [];
    let runningTotal = 0;

    for (const n of blobs) {
      const slashed = "/" + n.path;
      if (IMAGE_EXT.test(n.path)) continue; // handled by the image pass below
      if (
        SKIP_DIRS.test(slashed) ||
        BINARY_EXT.test(n.path) ||
        SKIP_FILES.test(n.path)
      ) {
        skipped.push(n.path);
        continue;
      }
      if ((n.size ?? 0) > MAX_FILE_BYTES) {
        skipped.push(`${n.path} (too large)`);
        continue;
      }
      if (selected.length >= MAX_FILES) {
        skipped.push(`${n.path} (file cap)`);
        continue;
      }
      if (runningTotal + (n.size ?? 0) > MAX_TOTAL_BYTES) {
        skipped.push(`${n.path} (size cap)`);
        continue;
      }
      selected.push(n);
      runningTotal += n.size ?? 0;
    }

    // Raster images: select within their own budget, skipping built/vendor dirs.
    const selectedImages: typeof blobs = [];
    let imageTotal = 0;
    for (const n of blobs) {
      if (!IMAGE_EXT.test(n.path)) continue;
      if (SKIP_DIRS.test("/" + n.path)) {
        skipped.push(n.path);
        continue;
      }
      if ((n.size ?? 0) > MAX_IMAGE_FILE_BYTES) {
        skipped.push(`${n.path} (image too large)`);
        continue;
      }
      if (selected.length + selectedImages.length >= MAX_FILES) {
        skipped.push(`${n.path} (file cap)`);
        continue;
      }
      if (imageTotal + (n.size ?? 0) > MAX_IMAGE_TOTAL_BYTES) {
        skipped.push(`${n.path} (image budget)`);
        continue;
      }
      selectedImages.push(n);
      imageTotal += n.size ?? 0;
    }

    if (selected.length === 0) {
      return c.json(
        { error: "No importable text files were found in that repo." },
        400,
      );
    }

    // Fetch each blob (base64) and decode to UTF-8 — inverse of the /push encoder.
    const files: Record<string, string> = {};
    const failed: string[] = [];
    for (const n of selected) {
      try {
        const blobRes = await gh(`/repos/${owner}/${repo}/git/blobs/${n.sha}`);
        if (!blobRes.ok) {
          failed.push(n.path);
          continue;
        }
        const blob = (await blobRes.json()) as {
          content: string;
          encoding: string;
        };
        if (blob.encoding !== "base64") {
          failed.push(n.path);
          continue;
        }
        const decoded = decodeURIComponent(
          escape(atob(blob.content.replace(/\n/g, ""))),
        );
        files["/" + n.path] = decoded;
      } catch {
        failed.push(n.path);
      }
    }

    // Raster images: keep the GitHub base64 as-is and store a data: URI (no
    // decode). The preview inlines these into the source that references them.
    for (const n of selectedImages) {
      try {
        const blobRes = await gh(`/repos/${owner}/${repo}/git/blobs/${n.sha}`);
        if (!blobRes.ok) {
          failed.push(n.path);
          continue;
        }
        const blob = (await blobRes.json()) as {
          content: string;
          encoding: string;
        };
        if (blob.encoding !== "base64") {
          failed.push(n.path);
          continue;
        }
        const ext = (n.path.split(".").pop() || "").toLowerCase();
        const mime = IMAGE_MIME[ext] || "application/octet-stream";
        const b64 = blob.content.replace(/\n/g, "");
        files["/" + n.path] = `data:${mime};base64,${b64}`;
      } catch {
        failed.push(n.path);
      }
    }

    if (Object.keys(files).length === 0) {
      return c.json(
        { error: "Failed to download any files from that repo." },
        502,
      );
    }

    // Create the project exactly like POST /api/projects does.
    const projectId = nanoid(10);
    const now = new Date().toISOString();
    const project = {
      id: projectId,
      userId,
      name: repoInfo.name || repo,
      description: `Imported from ${owner}/${repo}`,
      createdAt: now,
      updatedAt: now,
    };
    await kv.put(`user:${userId}:project:${projectId}`, JSON.stringify(project));

    // Capture the repo's runtime dependencies so the Sandpack preview can
    // install them — without this the preview fails with "module not found" on
    // every npm import (radix, class-variance-authority, etc.). Sandpack's
    // template manages react/react-dom itself, so drop those to avoid a clash.
    const dependencies: Record<string, string> = {};
    try {
      const pkgRaw = files["/package.json"];
      if (pkgRaw) {
        const pkg = JSON.parse(pkgRaw) as {
          dependencies?: Record<string, string>;
        };
        if (pkg.dependencies && typeof pkg.dependencies === "object") {
          for (const [name, ver] of Object.entries(pkg.dependencies)) {
            if (name === "react" || name === "react-dom") continue;
            if (typeof ver === "string") dependencies[name] = ver;
          }
        }
      }
    } catch {
      // Malformed package.json — preview falls back to its baseline deps.
    }

    const initialVersionData = {
      version: 1,
      createdAt: now,
      prompt: `Imported from https://github.com/${owner}/${repo} (${ref})`,
      files,
      dependencies,
    };
    await r2.put(`${projectId}/v1.json`, JSON.stringify(initialVersionData));
    await kv.put(`project:${projectId}:latest_version`, "1");

    return c.json(
      {
        project,
        version: 1,
        imported: Object.keys(files).length,
        skipped: skipped.length,
        failed: failed.length,
        truncated: tree.truncated ?? false,
      },
      201,
    );
  } catch (error) {
    console.error("GitHub import error:", error);
    return c.json(
      {
        error: "Failed to import from GitHub",
        detail: error instanceof Error ? error.message : String(error),
      },
      500,
    );
  }
});

export default githubRouter;
